/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IZunoGigs', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IZunoGigs__factory>
getContractFactory(name: 'ZunoEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ZunoEscrow__factory>
getContractFactory(name: 'ZunoGigs', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ZunoGigs__factory>
getContractFactory(name: 'ZunoProfile', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ZunoProfile__factory>
getContractFactory(name: 'MockCUSD', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockCUSD__factory>

  getContractAt(name: 'IZunoGigs', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IZunoGigs>
getContractAt(name: 'ZunoEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ZunoEscrow>
getContractAt(name: 'ZunoGigs', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ZunoGigs>
getContractAt(name: 'ZunoProfile', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ZunoProfile>
getContractAt(name: 'MockCUSD', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockCUSD>

  deployContract(name: 'IZunoGigs', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IZunoGigs>
deployContract(name: 'ZunoEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ZunoEscrow>
deployContract(name: 'ZunoGigs', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ZunoGigs>
deployContract(name: 'ZunoProfile', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ZunoProfile>
deployContract(name: 'MockCUSD', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockCUSD>

  deployContract(name: 'IZunoGigs', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IZunoGigs>
deployContract(name: 'ZunoEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ZunoEscrow>
deployContract(name: 'ZunoGigs', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ZunoGigs>
deployContract(name: 'ZunoProfile', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ZunoProfile>
deployContract(name: 'MockCUSD', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockCUSD>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  