/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ZunoProfile {
      
    export type ProfileStruct = {displayName: string, bio: string, avatarIpfsHash: string, skills: string[], isFreelancer: boolean, isClient: boolean, exists: boolean, createdAt: BigNumberish, updatedAt: BigNumberish}

    export type ProfileStructOutput = [displayName: string, bio: string, avatarIpfsHash: string, skills: string[], isFreelancer: boolean, isClient: boolean, exists: boolean, createdAt: bigint, updatedAt: bigint] & {displayName: string, bio: string, avatarIpfsHash: string, skills: string[], isFreelancer: boolean, isClient: boolean, exists: boolean, createdAt: bigint, updatedAt: bigint }
  
    }

  export interface ZunoProfileInterface extends Interface {
    getFunction(nameOrSignature: "createProfile" | "getProfile" | "hasProfile" | "isClient" | "isFreelancer" | "owner" | "renounceOwnership" | "totalProfiles" | "transferOwnership" | "updateProfile"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ProfileCreated" | "ProfileUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'createProfile', values: [string, string, string, string[], boolean, boolean]): string;
encodeFunctionData(functionFragment: 'getProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isClient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isFreelancer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalProfiles', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateProfile', values: [string, string, string, string[], boolean, boolean]): string;

    decodeFunctionResult(functionFragment: 'createProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFreelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalProfiles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateProfile', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProfileCreatedEvent {
      export type InputTuple = [user: AddressLike, displayName: string, isFreelancer: boolean, isClient: boolean];
      export type OutputTuple = [user: string, displayName: string, isFreelancer: boolean, isClient: boolean];
      export interface OutputObject {user: string, displayName: string, isFreelancer: boolean, isClient: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProfileUpdatedEvent {
      export type InputTuple = [user: AddressLike, displayName: string];
      export type OutputTuple = [user: string, displayName: string];
      export interface OutputObject {user: string, displayName: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZunoProfile extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZunoProfile;
    waitForDeployment(): Promise<this>;

    interface: ZunoProfileInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createProfile: TypedContractMethod<
      [displayName: string, bio: string, avatarIpfsHash: string, skills: string[], freelancer: boolean, client: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    getProfile: TypedContractMethod<
      [user: AddressLike, ],
      [ZunoProfile.ProfileStructOutput],
      'view'
    >
    

    
    hasProfile: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isClient: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isFreelancer: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalProfiles: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateProfile: TypedContractMethod<
      [displayName: string, bio: string, avatarIpfsHash: string, skills: string[], freelancer: boolean, client: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createProfile'): TypedContractMethod<
      [displayName: string, bio: string, avatarIpfsHash: string, skills: string[], freelancer: boolean, client: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProfile'): TypedContractMethod<
      [user: AddressLike, ],
      [ZunoProfile.ProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasProfile'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isClient'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isFreelancer'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalProfiles'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateProfile'): TypedContractMethod<
      [displayName: string, bio: string, avatarIpfsHash: string, skills: string[], freelancer: boolean, client: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProfileCreated'): TypedContractEvent<ProfileCreatedEvent.InputTuple, ProfileCreatedEvent.OutputTuple, ProfileCreatedEvent.OutputObject>;
getEvent(key: 'ProfileUpdated'): TypedContractEvent<ProfileUpdatedEvent.InputTuple, ProfileUpdatedEvent.OutputTuple, ProfileUpdatedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProfileCreated(address,string,bool,bool)': TypedContractEvent<ProfileCreatedEvent.InputTuple, ProfileCreatedEvent.OutputTuple, ProfileCreatedEvent.OutputObject>;
      ProfileCreated: TypedContractEvent<ProfileCreatedEvent.InputTuple, ProfileCreatedEvent.OutputTuple, ProfileCreatedEvent.OutputObject>;
    

      'ProfileUpdated(address,string)': TypedContractEvent<ProfileUpdatedEvent.InputTuple, ProfileUpdatedEvent.OutputTuple, ProfileUpdatedEvent.OutputObject>;
      ProfileUpdated: TypedContractEvent<ProfileUpdatedEvent.InputTuple, ProfileUpdatedEvent.OutputTuple, ProfileUpdatedEvent.OutputObject>;
    
    };
  }