/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ZunoGigs {
      
    export type GigStruct = {id: BigNumberish, owner: AddressLike, title: string, description: string, category: string, tags: string[], price: BigNumberish, deliveryDays: BigNumberish, metadataIpfsHash: string, active: boolean, createdAt: BigNumberish, updatedAt: BigNumberish}

    export type GigStructOutput = [id: bigint, owner: string, title: string, description: string, category: string, tags: string[], price: bigint, deliveryDays: bigint, metadataIpfsHash: string, active: boolean, createdAt: bigint, updatedAt: bigint] & {id: bigint, owner: string, title: string, description: string, category: string, tags: string[], price: bigint, deliveryDays: bigint, metadataIpfsHash: string, active: boolean, createdAt: bigint, updatedAt: bigint }
  
    }

  export interface ZunoGigsInterface extends Interface {
    getFunction(nameOrSignature: "createGig" | "deleteGig" | "getGig" | "getGigOwner" | "getGigPrice" | "getGigsByOwner" | "isGigActive" | "owner" | "renounceOwnership" | "totalGigs" | "transferOwnership" | "updateGig"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "GigCreated" | "GigDeleted" | "GigUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'createGig', values: [string, string, string, string[], BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'deleteGig', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGig', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGigOwner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGigPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGigsByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isGigActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalGigs', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateGig', values: [BigNumberish, string, string, string, string[], BigNumberish, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'createGig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deleteGig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGigOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGigPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGigsByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isGigActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalGigs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateGig', data: BytesLike): Result;
  }

  
    export namespace GigCreatedEvent {
      export type InputTuple = [gigId: BigNumberish, owner: AddressLike, title: string, price: BigNumberish];
      export type OutputTuple = [gigId: bigint, owner: string, title: string, price: bigint];
      export interface OutputObject {gigId: bigint, owner: string, title: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GigDeletedEvent {
      export type InputTuple = [gigId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [gigId: bigint, owner: string];
      export interface OutputObject {gigId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GigUpdatedEvent {
      export type InputTuple = [gigId: BigNumberish, owner: AddressLike, title: string, price: BigNumberish];
      export type OutputTuple = [gigId: bigint, owner: string, title: string, price: bigint];
      export interface OutputObject {gigId: bigint, owner: string, title: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZunoGigs extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZunoGigs;
    waitForDeployment(): Promise<this>;

    interface: ZunoGigsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createGig: TypedContractMethod<
      [title: string, description: string, category: string, tags: string[], price: BigNumberish, deliveryDays: BigNumberish, metadataIpfsHash: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    deleteGig: TypedContractMethod<
      [gigId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getGig: TypedContractMethod<
      [gigId: BigNumberish, ],
      [ZunoGigs.GigStructOutput],
      'view'
    >
    

    
    getGigOwner: TypedContractMethod<
      [gigId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getGigPrice: TypedContractMethod<
      [gigId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getGigsByOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    isGigActive: TypedContractMethod<
      [gigId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalGigs: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateGig: TypedContractMethod<
      [gigId: BigNumberish, title: string, description: string, category: string, tags: string[], price: BigNumberish, deliveryDays: BigNumberish, metadataIpfsHash: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createGig'): TypedContractMethod<
      [title: string, description: string, category: string, tags: string[], price: BigNumberish, deliveryDays: BigNumberish, metadataIpfsHash: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deleteGig'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getGig'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [ZunoGigs.GigStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getGigOwner'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getGigPrice'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getGigsByOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isGigActive'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalGigs'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateGig'): TypedContractMethod<
      [gigId: BigNumberish, title: string, description: string, category: string, tags: string[], price: BigNumberish, deliveryDays: BigNumberish, metadataIpfsHash: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'GigCreated'): TypedContractEvent<GigCreatedEvent.InputTuple, GigCreatedEvent.OutputTuple, GigCreatedEvent.OutputObject>;
getEvent(key: 'GigDeleted'): TypedContractEvent<GigDeletedEvent.InputTuple, GigDeletedEvent.OutputTuple, GigDeletedEvent.OutputObject>;
getEvent(key: 'GigUpdated'): TypedContractEvent<GigUpdatedEvent.InputTuple, GigUpdatedEvent.OutputTuple, GigUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'GigCreated(uint256,address,string,uint256)': TypedContractEvent<GigCreatedEvent.InputTuple, GigCreatedEvent.OutputTuple, GigCreatedEvent.OutputObject>;
      GigCreated: TypedContractEvent<GigCreatedEvent.InputTuple, GigCreatedEvent.OutputTuple, GigCreatedEvent.OutputObject>;
    

      'GigDeleted(uint256,address)': TypedContractEvent<GigDeletedEvent.InputTuple, GigDeletedEvent.OutputTuple, GigDeletedEvent.OutputObject>;
      GigDeleted: TypedContractEvent<GigDeletedEvent.InputTuple, GigDeletedEvent.OutputTuple, GigDeletedEvent.OutputObject>;
    

      'GigUpdated(uint256,address,string,uint256)': TypedContractEvent<GigUpdatedEvent.InputTuple, GigUpdatedEvent.OutputTuple, GigUpdatedEvent.OutputObject>;
      GigUpdated: TypedContractEvent<GigUpdatedEvent.InputTuple, GigUpdatedEvent.OutputTuple, GigUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }