/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { Lock, LockInterface } from "../Lock.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_unlockTime",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "unlockTime",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060405161011738038061011783398101604081905261002e91610047565b5f55600180546001600160a01b0319163317905561005e565b5f60208284031215610057575f80fd5b5051919050565b60ad8061006a5f395ff3fe6080604052348015600e575f80fd5b50600436106030575f3560e01c8063251c1aa31460345780638da5cb5b14604e575b5f80fd5b603b5f5481565b6040519081526020015b60405180910390f35b6001546060906001600160a01b031681565b6040516001600160a01b039091168152602001604556fea2646970667358221220e6d7542d11669bba054ea39861d0ce90c70054a7df21fdbcccd2ee590f1cb9f864736f6c63430008180033";

  
      type LockConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LockConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Lock__factory extends ContractFactory {
    
      constructor(...args: LockConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_unlockTime: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_unlockTime, overrides || {});
    };
    override deploy(_unlockTime: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_unlockTime, overrides || {}) as Promise<Lock & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Lock__factory {
      return super.connect(runner) as Lock__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LockInterface {
      return new Interface(_abi) as LockInterface;
    }
    
    override attach(address: string | Addressable): Lock {
      return super.attach(address) as Lock;
    }
  static connect(address: string, runner?: ContractRunner | null): Lock {
      return new Contract(address, _abi, runner) as unknown as Lock;
    }
  }

  
  