/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IZunoGigs, IZunoGigsInterface } from "../../ZunoEscrow.sol/IZunoGigs.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "gigId",
        "type": "uint256"
      }
    ],
    "name": "getGigOwner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "gigId",
        "type": "uint256"
      }
    ],
    "name": "getGigPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "gigId",
        "type": "uint256"
      }
    ],
    "name": "isGigActive",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IZunoGigs__factory {
    static readonly abi = _abi;
    static createInterface(): IZunoGigsInterface {
      return new Interface(_abi) as IZunoGigsInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IZunoGigs {
      return new Contract(address, _abi, runner) as unknown as IZunoGigs;
    }
  }
  