/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IZunoEscrow {
      
    export type OrderStruct = {id: BigNumberish, gigId: BigNumberish, client: AddressLike, freelancer: AddressLike, amount: BigNumberish, platformFee: BigNumberish, status: BigNumberish, createdAt: BigNumberish, updatedAt: BigNumberish}

    export type OrderStructOutput = [id: bigint, gigId: bigint, client: string, freelancer: string, amount: bigint, platformFee: bigint, status: bigint, createdAt: bigint, updatedAt: bigint] & {id: bigint, gigId: bigint, client: string, freelancer: string, amount: bigint, platformFee: bigint, status: bigint, createdAt: bigint, updatedAt: bigint }
  
    }

  export interface IZunoEscrowInterface extends Interface {
    getFunction(nameOrSignature: "getOrder"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getOrder', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
  }

  

  export interface IZunoEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): IZunoEscrow;
    waitForDeployment(): Promise<this>;

    interface: IZunoEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [IZunoEscrow.OrderStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [IZunoEscrow.OrderStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }