/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ZunoReviews {
      
    export type ReviewStruct = {orderId: BigNumberish, reviewer: AddressLike, reviewee: AddressLike, rating: BigNumberish, comment: string, createdAt: BigNumberish}

    export type ReviewStructOutput = [orderId: bigint, reviewer: string, reviewee: string, rating: bigint, comment: string, createdAt: bigint] & {orderId: bigint, reviewer: string, reviewee: string, rating: bigint, comment: string, createdAt: bigint }
  
    }

  export interface ZunoReviewsInterface extends Interface {
    getFunction(nameOrSignature: "escrowContract" | "getAverageRating" | "getReview" | "hasReviewed" | "owner" | "renounceOwnership" | "submitReview" | "totalRatingPoints" | "totalReviewCount" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ReviewSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'escrowContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAverageRating', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReview', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasReviewed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitReview', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'totalRatingPoints', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalReviewCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'escrowContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAverageRating', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReview', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasReviewed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitReview', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRatingPoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReviewCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReviewSubmittedEvent {
      export type InputTuple = [orderId: BigNumberish, reviewer: AddressLike, reviewee: AddressLike, rating: BigNumberish];
      export type OutputTuple = [orderId: bigint, reviewer: string, reviewee: string, rating: bigint];
      export interface OutputObject {orderId: bigint, reviewer: string, reviewee: string, rating: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZunoReviews extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZunoReviews;
    waitForDeployment(): Promise<this>;

    interface: ZunoReviewsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    escrowContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAverageRating: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getReview: TypedContractMethod<
      [orderId: BigNumberish, reviewer: AddressLike, ],
      [ZunoReviews.ReviewStructOutput],
      'view'
    >
    

    
    hasReviewed: TypedContractMethod<
      [orderId: BigNumberish, reviewer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    submitReview: TypedContractMethod<
      [orderId: BigNumberish, rating: BigNumberish, comment: string, ],
      [void],
      'nonpayable'
    >
    

    
    totalRatingPoints: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    totalReviewCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'escrowContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAverageRating'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getReview'): TypedContractMethod<
      [orderId: BigNumberish, reviewer: AddressLike, ],
      [ZunoReviews.ReviewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasReviewed'): TypedContractMethod<
      [orderId: BigNumberish, reviewer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitReview'): TypedContractMethod<
      [orderId: BigNumberish, rating: BigNumberish, comment: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalRatingPoints'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalReviewCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReviewSubmitted'): TypedContractEvent<ReviewSubmittedEvent.InputTuple, ReviewSubmittedEvent.OutputTuple, ReviewSubmittedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReviewSubmitted(uint256,address,address,uint8)': TypedContractEvent<ReviewSubmittedEvent.InputTuple, ReviewSubmittedEvent.OutputTuple, ReviewSubmittedEvent.OutputObject>;
      ReviewSubmitted: TypedContractEvent<ReviewSubmittedEvent.InputTuple, ReviewSubmittedEvent.OutputTuple, ReviewSubmittedEvent.OutputObject>;
    
    };
  }