/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZunoEscrowDispute } from './IZunoEscrowDispute.js';
export type { ZunoDispute } from './ZunoDispute.js';