/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ZunoDispute {
      
    export type DisputeStruct = {id: BigNumberish, orderId: BigNumberish, raisedBy: AddressLike, reason: string, status: BigNumberish, resolvedBy: AddressLike, clientRefundBps: BigNumberish, createdAt: BigNumberish, resolvedAt: BigNumberish}

    export type DisputeStructOutput = [id: bigint, orderId: bigint, raisedBy: string, reason: string, status: bigint, resolvedBy: string, clientRefundBps: bigint, createdAt: bigint, resolvedAt: bigint] & {id: bigint, orderId: bigint, raisedBy: string, reason: string, status: bigint, resolvedBy: string, clientRefundBps: bigint, createdAt: bigint, resolvedAt: bigint }
  
    }

  export interface ZunoDisputeInterface extends Interface {
    getFunction(nameOrSignature: "addArbitrator" | "disputeByOrder" | "escrowContract" | "getDispute" | "getDisputeByOrder" | "isArbitrator" | "owner" | "raiseDispute" | "removeArbitrator" | "renounceOwnership" | "resolveDispute" | "totalDisputes" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ArbitratorAdded" | "ArbitratorRemoved" | "DisputeRaised" | "DisputeResolved" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'addArbitrator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'disputeByOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrowContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDisputeByOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isArbitrator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'removeArbitrator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalDisputes', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addArbitrator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeByOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDisputeByOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isArbitrator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeArbitrator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDisputes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ArbitratorAddedEvent {
      export type InputTuple = [arbitrator: AddressLike];
      export type OutputTuple = [arbitrator: string];
      export interface OutputObject {arbitrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArbitratorRemovedEvent {
      export type InputTuple = [arbitrator: AddressLike];
      export type OutputTuple = [arbitrator: string];
      export interface OutputObject {arbitrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeRaisedEvent {
      export type InputTuple = [disputeId: BigNumberish, orderId: BigNumberish, raisedBy: AddressLike];
      export type OutputTuple = [disputeId: bigint, orderId: bigint, raisedBy: string];
      export interface OutputObject {disputeId: bigint, orderId: bigint, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [disputeId: BigNumberish, orderId: BigNumberish, resolvedBy: AddressLike, clientRefundBps: BigNumberish];
      export type OutputTuple = [disputeId: bigint, orderId: bigint, resolvedBy: string, clientRefundBps: bigint];
      export interface OutputObject {disputeId: bigint, orderId: bigint, resolvedBy: string, clientRefundBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZunoDispute extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZunoDispute;
    waitForDeployment(): Promise<this>;

    interface: ZunoDisputeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addArbitrator: TypedContractMethod<
      [arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    disputeByOrder: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    escrowContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getDispute: TypedContractMethod<
      [disputeId: BigNumberish, ],
      [ZunoDispute.DisputeStructOutput],
      'view'
    >
    

    
    getDisputeByOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [ZunoDispute.DisputeStructOutput],
      'view'
    >
    

    
    isArbitrator: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [orderId: BigNumberish, reason: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    removeArbitrator: TypedContractMethod<
      [arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [disputeId: BigNumberish, clientRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalDisputes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addArbitrator'): TypedContractMethod<
      [arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeByOrder'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'escrowContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDispute'): TypedContractMethod<
      [disputeId: BigNumberish, ],
      [ZunoDispute.DisputeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDisputeByOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [ZunoDispute.DisputeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isArbitrator'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [orderId: BigNumberish, reason: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeArbitrator'): TypedContractMethod<
      [arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [disputeId: BigNumberish, clientRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalDisputes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ArbitratorAdded'): TypedContractEvent<ArbitratorAddedEvent.InputTuple, ArbitratorAddedEvent.OutputTuple, ArbitratorAddedEvent.OutputObject>;
getEvent(key: 'ArbitratorRemoved'): TypedContractEvent<ArbitratorRemovedEvent.InputTuple, ArbitratorRemovedEvent.OutputTuple, ArbitratorRemovedEvent.OutputObject>;
getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'ArbitratorAdded(address)': TypedContractEvent<ArbitratorAddedEvent.InputTuple, ArbitratorAddedEvent.OutputTuple, ArbitratorAddedEvent.OutputObject>;
      ArbitratorAdded: TypedContractEvent<ArbitratorAddedEvent.InputTuple, ArbitratorAddedEvent.OutputTuple, ArbitratorAddedEvent.OutputObject>;
    

      'ArbitratorRemoved(address)': TypedContractEvent<ArbitratorRemovedEvent.InputTuple, ArbitratorRemovedEvent.OutputTuple, ArbitratorRemovedEvent.OutputObject>;
      ArbitratorRemoved: TypedContractEvent<ArbitratorRemovedEvent.InputTuple, ArbitratorRemovedEvent.OutputTuple, ArbitratorRemovedEvent.OutputObject>;
    

      'DisputeRaised(uint256,uint256,address)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(uint256,uint256,address,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }