/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IZunoGigsInterface extends Interface {
    getFunction(nameOrSignature: "getGigOwner" | "getGigPrice" | "isGigActive"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getGigOwner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGigPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isGigActive', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getGigOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGigPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isGigActive', data: BytesLike): Result;
  }

  

  export interface IZunoGigs extends BaseContract {
    
    connect(runner?: ContractRunner | null): IZunoGigs;
    waitForDeployment(): Promise<this>;

    interface: IZunoGigsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getGigOwner: TypedContractMethod<
      [gigId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getGigPrice: TypedContractMethod<
      [gigId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    isGigActive: TypedContractMethod<
      [gigId: BigNumberish, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getGigOwner'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getGigPrice'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isGigActive'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }