/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ZunoEscrow {
      
    export type OrderStruct = {id: BigNumberish, gigId: BigNumberish, client: AddressLike, freelancer: AddressLike, amount: BigNumberish, platformFee: BigNumberish, status: BigNumberish, createdAt: BigNumberish, updatedAt: BigNumberish}

    export type OrderStructOutput = [id: bigint, gigId: bigint, client: string, freelancer: string, amount: bigint, platformFee: bigint, status: bigint, createdAt: bigint, updatedAt: bigint] & {id: bigint, gigId: bigint, client: string, freelancer: string, amount: bigint, platformFee: bigint, status: bigint, createdAt: bigint, updatedAt: bigint }
  
    }

  export interface ZunoEscrowInterface extends Interface {
    getFunction(nameOrSignature: "approveDelivery" | "cUSD" | "cancelOrder" | "getOrder" | "getOrdersByClient" | "getOrdersByFreelancer" | "gigsContract" | "markDelivered" | "owner" | "placeOrder" | "platformFeeBps" | "raiseDispute" | "renounceOwnership" | "resolveDispute" | "setPlatformFee" | "setTreasury" | "totalOrders" | "transferOwnership" | "treasury"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OrderCancelled" | "OrderCompleted" | "OrderDelivered" | "OrderDisputed" | "OrderPlaced" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'approveDelivery', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cUSD', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOrdersByClient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getOrdersByFreelancer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'gigsContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'markDelivered', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'platformFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalOrders', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approveDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cUSD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrdersByClient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrdersByFreelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gigsContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markDelivered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  }

  
    export namespace OrderCancelledEvent {
      export type InputTuple = [orderId: BigNumberish, client: AddressLike, refund: BigNumberish];
      export type OutputTuple = [orderId: bigint, client: string, refund: bigint];
      export interface OutputObject {orderId: bigint, client: string, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderCompletedEvent {
      export type InputTuple = [orderId: BigNumberish, freelancer: AddressLike, payout: BigNumberish];
      export type OutputTuple = [orderId: bigint, freelancer: string, payout: bigint];
      export interface OutputObject {orderId: bigint, freelancer: string, payout: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderDeliveredEvent {
      export type InputTuple = [orderId: BigNumberish];
      export type OutputTuple = [orderId: bigint];
      export interface OutputObject {orderId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderDisputedEvent {
      export type InputTuple = [orderId: BigNumberish, raisedBy: AddressLike];
      export type OutputTuple = [orderId: bigint, raisedBy: string];
      export interface OutputObject {orderId: bigint, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderPlacedEvent {
      export type InputTuple = [orderId: BigNumberish, gigId: BigNumberish, client: AddressLike, freelancer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: bigint, gigId: bigint, client: string, freelancer: string, amount: bigint];
      export interface OutputObject {orderId: bigint, gigId: bigint, client: string, freelancer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZunoEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZunoEscrow;
    waitForDeployment(): Promise<this>;

    interface: ZunoEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveDelivery: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cUSD: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [ZunoEscrow.OrderStructOutput],
      'view'
    >
    

    
    getOrdersByClient: TypedContractMethod<
      [client: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getOrdersByFreelancer: TypedContractMethod<
      [freelancer: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    gigsContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    markDelivered: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeOrder: TypedContractMethod<
      [gigId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    platformFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [orderId: BigNumberish, clientRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPlatformFee: TypedContractMethod<
      [_feeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalOrders: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveDelivery'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cUSD'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [ZunoEscrow.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrdersByClient'): TypedContractMethod<
      [client: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getOrdersByFreelancer'): TypedContractMethod<
      [freelancer: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'gigsContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'markDelivered'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeOrder'): TypedContractMethod<
      [gigId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'platformFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [orderId: BigNumberish, clientRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPlatformFee'): TypedContractMethod<
      [_feeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalOrders'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'OrderCancelled'): TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
getEvent(key: 'OrderCompleted'): TypedContractEvent<OrderCompletedEvent.InputTuple, OrderCompletedEvent.OutputTuple, OrderCompletedEvent.OutputObject>;
getEvent(key: 'OrderDelivered'): TypedContractEvent<OrderDeliveredEvent.InputTuple, OrderDeliveredEvent.OutputTuple, OrderDeliveredEvent.OutputObject>;
getEvent(key: 'OrderDisputed'): TypedContractEvent<OrderDisputedEvent.InputTuple, OrderDisputedEvent.OutputTuple, OrderDisputedEvent.OutputObject>;
getEvent(key: 'OrderPlaced'): TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OrderCancelled(uint256,address,uint256)': TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
      OrderCancelled: TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
    

      'OrderCompleted(uint256,address,uint256)': TypedContractEvent<OrderCompletedEvent.InputTuple, OrderCompletedEvent.OutputTuple, OrderCompletedEvent.OutputObject>;
      OrderCompleted: TypedContractEvent<OrderCompletedEvent.InputTuple, OrderCompletedEvent.OutputTuple, OrderCompletedEvent.OutputObject>;
    

      'OrderDelivered(uint256)': TypedContractEvent<OrderDeliveredEvent.InputTuple, OrderDeliveredEvent.OutputTuple, OrderDeliveredEvent.OutputObject>;
      OrderDelivered: TypedContractEvent<OrderDeliveredEvent.InputTuple, OrderDeliveredEvent.OutputTuple, OrderDeliveredEvent.OutputObject>;
    

      'OrderDisputed(uint256,address)': TypedContractEvent<OrderDisputedEvent.InputTuple, OrderDisputedEvent.OutputTuple, OrderDisputedEvent.OutputObject>;
      OrderDisputed: TypedContractEvent<OrderDisputedEvent.InputTuple, OrderDisputedEvent.OutputTuple, OrderDisputedEvent.OutputObject>;
    

      'OrderPlaced(uint256,uint256,address,address,uint256)': TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
      OrderPlaced: TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }